FROM tf-cpu:1.9.0
ENV PANDAS_VERSION=0.24.0
RUN pip3.6 install pandas==${PANDAS_VERSION}
ENV KERAS_VERSION=2.2.4
# install Keras using pip
RUN pip3.6 install keras==${KERAS_VERSION}
RUN rm -f /usr/bin/python3 && ln -s /usr/bin/python3.6 /usr/bin/python3
RUN apt-get install -y gcc python3.6-dev
WORKDIR /root
